### ISSUE TITLE
may I know how to make the build not to add random number after assets?

### ISSUE THREAD

**Issue by adamchenwei** [alexnoz/webpack-pug-scss-boilerplate#7]
right now its generating slider-1.b7697e60.jpg . How to shut it off? since its causing the direct href linked assets to fail to wire up...

**Comment by alexnoz** [comment]
Do you have this problem with images or with `<link href="...">`? Images shouldn't cause problems since webpack substitutes the original path with the hashed one in `index.html` so that the path and a processed image name match.

Of course, you can prevent hash generation by removing the `[hash]` part from an output asset filename, e.g.:
```javascript
// before
'/[name].[chunkhash:8].js'

// after
'/[name].js'
```
Here are the lines in `webpack.config.js` you might want to change:

[js](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L107) (and the next line)
[css](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L168) (and the next line)
[images](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L187)
[fonts](https://github.com/alexnoz/webpack-pug-scss-boilerplate/blob/master/webpack.config.js#L92)

Note, however, that it will disable cache busting, more on that [here](https://webpack.js.org/guides/caching/).

**Comment by adamchenwei** [comment]
@alexnoz thanks for the tip! very nice boilerplate 👍
